service: service-365display
provider:
  name: aws
  runtime: rust
  logs:
    websocket: true
  environment:
    tableName: ${self:custom.tableName}
plugins:
  - serverless-rust

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-connections

package:
  individually: true
functions:
  connect:
    handler: display
    events:
      - websocket: $connect
  disconnect:
    handler: display
    events:
      - websocket: $disconnect
  default:
    handler: display
    events:
      - websocket: $default

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
