service: service-365display
provider:
  name: aws
  runtime: rust
  logs:
    websocket: true
  environment:
    connectionsTable: ${self:custom.connectionsTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        # https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-control-access-iam.html
        - "arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/${self:custom.stage}/POST/@connections/*"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ConnectionsTable, Arn]

plugins:
  - serverless-rust

custom:
  stage: ${opt:stage, self:provider.stage}
  connectionsTable: ${self:custom.stage}-connections

package:
  individually: true
functions:
  connect:
    handler: display
    events:
      - websocket: $connect
  disconnect:
    handler: display
    events:
      - websocket: $disconnect
  default:
    handler: display
    events:
      - websocket: $default

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.connectionsTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
