service: service-365display
provider:
  name: aws
  runtime: rust
  logs:
    websocket: true
plugins:
  - serverless-rust

package:
  individually: true
functions:
  connect:
    handler: display
    events:
      - websocket: $connect
  disconnect:
    handler: display
    events:
      - websocket: $disconnect
  default:
    handler: display
    events:
      - websocket: $default
